2018-08-25 20:03:46,915 ERROR: Exception on /user/lu290536 [GET] [in /home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/lu2905363/PycharmProjects/flask/app/routes.py", line 95, in user
    return render_template('user.html', user=user, posts=posts.items, next_url=next_url, prev_url=prev_url)
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/lu2905363/PycharmProjects/flask/app/templates/base.html", line 55, in template
    {% block app_content %}{% endblock %}
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "/home/lu2905363/PycharmProjects/flask/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/lu2905363/PycharmProjects/flask/app/templates/base.html", line 55, in template
    {% block app_content %}{% endblock %}
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/jinja2/parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/jinja2/parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/jinja2/parser.py", line 268, in parse_block
    node.body = self.parse_statements(('name:endblock',), drop_needle=True)
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/jinja2/parser.py", line 170, in parse_statements
    self.fail_eof(end_tokens)
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/jinja2/parser.py", line 104, in fail_eof
    return self._fail_ut_eof(None, stack, lineno)
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/jinja2/parser.py", line 90, in _fail_ut_eof
    self.fail(' '.join(message), lineno)
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/jinja2/parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2018-08-25 20:04:42,867 INFO: Microblog startup [in /home/lu2905363/PycharmProjects/flask/app/__init__.py:50]
2018-08-25 20:12:13,555 INFO: Microblog startup [in /home/lu2905363/PycharmProjects/flask/app/__init__.py:50]
2018-08-25 20:12:19,243 ERROR: Exception on /user/lu290536 [GET] [in /home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/lu2905363/PycharmProjects/flask/app/routes.py", line 95, in user
    return render_template('user.html', user=user, posts=posts.items, next_url=next_url, prev_url=prev_url)
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/lu2905363/PycharmProjects/flask/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/lu2905363/PycharmProjects/flask/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/home/lu2905363/PycharmProjects/flask/app/templates/base.html", line 55, in block "content"
    {% block app_content %}{% endblock %}
  File "/home/lu2905363/PycharmProjects/flask/app/templates/user.html", line 10, in block "app_content"
    {% if user.last_seen %}<p>Last seen on: {{ moment(user.last_seen.isoformat()).format('LLL')}}</p>{% endif %}
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/flask_moment.py", line 83, in format
    return self._render("format('%s')" % fmt, refresh)
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/flask_moment.py", line 76, in _render
    t = self._timestamp_as_iso_8601(self.timestamp)
  File "/home/lu2905363/PycharmProjects/flask/venv/lib/python3.6/site-packages/flask_moment.py", line 73, in _timestamp_as_iso_8601
    return timestamp.strftime('%Y-%m-%dT%H:%M:%S' + tz)
AttributeError: 'str' object has no attribute 'strftime'
2018-08-25 20:14:16,008 INFO: Microblog startup [in /home/lu2905363/PycharmProjects/flask/app/__init__.py:50]
